### ISSUE TITLE
Enable users to define their own temp folder

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.forest#5]
We use parallel processing to speed up analysis with the `statsGRASS` function. Since some of the layers are stored temporarily we run into storage issues and get an error message 

`sh: 1: cannot create /tmp/Rtmpe3Ce80/file41787aa11ae6.err: No space left on device`

If we could change the folder where the internal function store temporary data, this would help us because we could just switch to a bigger storage unit. 

@goergen95 

@Ohm-Np for your information

**Comment by goergen95** [comment]
Hi @Jo-Schie, 
thanks for this very sensible suggestion. I added a `.tmpdir` argument to the `statsGRASS()` function that can be used to declare a used defined directory where the GRASS rundir will be located. The default behavior will stil towards the system wide tmp directory. Please check it out if it works for you. Otherwise feel free to reopen.
